version: '3'

services:
  frontend:
    image: sudmed/time-app-frontend-dev
    restart: always
    ports:
      - '3000:3000'
  backend:
    image: sudmed/time-app-backend-dev
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PORT: '3306'
      MYSQL_PASSWORD: strong_password
      MYSQL_DB: app_db
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: strong_password
      MYSQL_DATABASE: app_db
    volumes:
      - mysql_data_pub:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'

volumes:
  mysql_data_pub:
